pragma solidity >=0.4.0 <0.9.0;


function Visibility ==>
public 
private 
internal
external

PRIVATE VISIBILITY = 

ONLY VISIBLE INSIDE THE CONTRACTS IE 
YOU CAN USE THEN IN STATE VARIABLES AND FUNCTION BUT IT CAN ONLY BE CALLED 
FROM INSIDE THE SMART CONTRACT BUT CANT BE CALLED OUTSIDE

INTERNAL VISIBILITY == ONLY VISIBLE INSIDE THE CONTRACT AND CHILD CONTRACT


PUBLIC VISIBILITY = VISIBILITY IS OPEN TO ALL CONTRACT AND EOAS 


EXTERNAL VISIBILITY = VISIBILITY POSSIBLE FOR OTHER CONTRACTS AND ACCOUNTS 


